### ISSUE TITLE
Bug: Could not add tuya account and camera

### ISSUE THREAD

**Issue by smartmatic** [donavanbecker/homebridge-tuya-camera#1]
### Describe The Bug

No access possible for devices linked in my Smart Life App and tuya IoT account

### To Reproduce

Try to link Smart Life account via UI

### Expected behavior

Camera should be added to get a URL for the stream

### Relevant log output

```shell
[08/01/2022, 20:17:13] [TuyaCamera] Attention⚠️ ⚠️ ⚠️ ! You get an error!
[08/01/2022, 20:17:13] [TuyaCamera] Please confirm that the Access ID and Access Secret of the Smart Home PaaS project you are using were created after May 25, 2021.
[08/01/2022, 20:17:13] [TuyaCamera] Please linked devices by using Tuya Smart or Smart Life app in your cloud project.
[08/01/2022, 20:17:13] [TuyaCamera] Failed to get device information. Please check if the config.json is correct.
```

### Config for homebridge-tuya-camera

```shell
{
           "name": "TuyaCamera",
           "username": "my Smart Life Username",
           "password": "my Smart Life PW",
           "accessId": "my tuya IoT accessID",
           "accessKey": "my tuya IoT accessKey",
           "lang": "en",
           "projectType": "2",
           "appSchema": "smartlife",
           "countryCode": 49,
           "platform": "TuyaCamera"
       }
```

### Node.js Version

v14.18.1

### NPM Version

v8.1.4

### Homebridge Version

v1.4.0-beta.4

### Homebridge TuyaCamera Plugin Version

v0.0.1

### Homebridge Config UI X Plugin Version

 v4.41.5

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
I have only tried project type: `PaaS` and PaaS Platform `Tuya Smart`

**Comment by smartmatic** [comment]
OK i can try it with the tuya app but the install guide from tuya-homebridge reocmmend in step 4 to use „Smart Home“ as project type and not „PaaS“.

[https://github.com/tuya/tuya-homebridge/wiki/Tuya-IoT-Platform-Configuration-Guide-Using-Smart-Home-PaaS?_source=d8fba44feeef4757f7f22a14c2295f3f](url)

Personally i am using tuya-homebridge since some month and all my tuya projects does not work with project type „Paas“. With „Smart Home“ as project type they do!

What ist still not clear for me how to get the stream URL once the config-ui settings are correct?

**Comment by smartmatic** [comment]
Next attempt. Added my camera in tuya app and created a new project in tuya IoT and linked the app with the project.
Then i have entered the new access and secret key into the plugin.
But the error message remains the same

`[09/01/2022, 11:45:06] [TuyaCamera] Attention⚠️ ⚠️ ⚠️ ! You get an error!
[09/01/2022, 11:45:06] [TuyaCamera] Please confirm that the Access ID and Access Secret of the Smart Home PaaS project you are using were created after May 25, 2021.
[09/01/2022, 11:45:06] [TuyaCamera] Please linked devices by using Tuya Smart or Smart Life app in your cloud project.
[09/01/2022, 11:45:06] [TuyaCamera] Failed to get device information. Please check if the config.json is correct.`

Here the new config

`{
            "name": "TuyaCamera",
            "username": "my tuya app username",
            "password": "my tuya app password",
            "accessId": "my tuya IoT ID",
            "accessKey": "my tuya IoT Key",
            "lang": "en",
            "projectType": "2", --> PaaS selected in the Plugin.
            "appSchema": "tuyaSmart",
            "countryCode": 49,
            "platform": "TuyaCamera"
        }`

**Comment by younesqwe** [comment]
I got the same problem with smart life

**Comment by smartmatic** [comment]
@smartmatic Do you plan to spend some time for further development for this plugin?
I am really interested and would to support you with testing!

I tried to find the RTSP Url vial Device Explorer in tuya IoT Portal but i could not find it!
Do you know where to find the RTSP  URL once the device is available in tuya IoT Portal?

**Comment by donavanbecker** [comment]
My plan is to work with the developer of homebridge-camera-ffmpeg, and make the tuya camera Available through that plugin, using this plugin to get the HLS url.

**Comment by donavanbecker** [comment]
@smartmatic Probably once he has hksv pushed out for camera-ffmpeg. Then we can focus on it.

**Comment by donavanbecker** [comment]
@smartmatic, can you see if the new version works for you to log into?

**Comment by smartmatic** [comment]
@donavanbecker Looks like the login works now! But now i get the following error.

`[TuyaCamera] Failed to get device information. Please check if the config.json is correct `

Cam is Online. Do i need to set username and password for the cam?
If yes where to config?

**Comment by donavanbecker** [comment]
@smartmatic Can you enable debug logging and send me more info?

**Comment by smartmatic** [comment]
> @smartmatic Can you enable debug logging and send me more info?

Debug logging is enabled but the only error i get is the one from my previous post

**Comment by younesqwe** [comment]
is there a way to get the rtsp url of my tuya camera ? until everything is settled

**Comment by dehness** [comment]
From what I've read in other Tuya related Homebridge issues, it might be a problem on Tuya's end.

**Comment by seekoner** [comment]
@donavanbecker  i have the same exact issue than @smartmatic and same response from logs, i'm very happy that someone is finally doing something related to CCTV integration in Homekit, however i dont understand your 
"Tuya 
test
test"
thing :p 
i hope for an update soon
keep up good work

**Comment by derpate1989** [comment]
i have the same issue with Same error Text.

**Comment by smartmatic** [comment]
@donavanbecker In the meantime i've done some additional tests. I used the Tuya Home Assistant integration and the it was very easy to add the camera and to open the stream within Home Assistant. Responsetime was very good!

So i guess technical wise is everything ready on Tuya's IoT Plattform. Then i added the camera to Apple Home App with the Home Assistant Homekit integration. In Home App i was able to see the Stream preview but could not open the stream.

But i think as it is basically possible to use the stream in Home Assistant the Tuya IoT API works.

Questions is why can't Homebridge open the Stream once the credentials are added into the plugin?

Do you have the time to further debug this behaviour?

**Comment by donavanbecker** [comment]
@smartmatic can you provide home assistant links?

**Comment by smartmatic** [comment]
> @smartmatic can you provide home assistant links?

I can't provide something specific as the basic integration works exactly like for Homebridge. So i used my Access-ID und Secret Key from the Tuya IoT Project and added these information together with my Tuya App account credentials into the Home Assistant Integration. 

[https://www.home-assistant.io/integrations/tuya/](url)

The camera was automatically detected from Home Assistant once the cam was added to Tuya App and Online

**Comment by Wazza151** [comment]
> My plan is to work with the developer of homebridge-camera-ffmpeg, and make the tuya camera Available through that plugin, using this plugin to get the HLS url.

@donavanbecker hi, just wondering if there is any update on this?
