### ISSUE TITLE
The Plugin won't get the device information.

### ISSUE THREAD

**Issue by Kratoskate28** [donavanbecker/homebridge-tuya-camera#2]
### Describe The Bug

I was wandering why I wouldn't get any information from the plugin, so I checked the config.json and everything was correct but still wont get the RTSP Url from my tuya camera. The message I get every time is the folowing: "Failed to get device information. Please check if the config.json is correct."

### To Reproduce

Fill in the config.json, then restart the homebridge, then look for [TuyaCamera] .... in homebridge terminal.]

### Expected behavior

I did expect everything to be ok and getting the rtsp url.

### Relevant log output

```shell
..
```

### Config for homebridge-tuya-camera

```shell
{
            "name": "TuyaCamera",
            "username": "XXXXXXXXXXXXX@gmail.com",
            "password": "XXXXXXXXXXXXXXXXXXXX",
            "accessId": "XXXXXXXXXXXXXXXXXXXXXXXXX",
            "accessKey": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "lang": "en",
            "projectType": "2",
            "appSchema": "smartlife",
            "countryCode": 352,
            "localhttp": false,
            "HLSorRTSP": "rtsp",
            "refreshRate": 1800,
            "logging": "none",
            "platform": "TuyaCamera"
        }
```

### Node.js Version

v16.13.2

### NPM Version

v8.1.2

### Homebridge Version

v1.4.0

### Homebridge TuyaCamera Plugin Version

v0.0.2

### Homebridge Config UI X Plugin Version

v4.42.0

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
Haven't been able to test SmartLife support. But Tuya works.

**Comment by Kratoskate28** [comment]
I can't get it to work, did I do something wrong
<img width="844" alt="Bildschirmfoto 2022-01-29 um 21 29 10" src="https://user-images.githubusercontent.com/85301844/151676643-a9339d5d-6dfb-4323-bf55-f6edaee0fdc3.png">

**Comment by donavanbecker** [comment]
Logging is set to none

**Comment by Kratoskate28** [comment]
I tried all kind of logging settings, but it still doesn't work.

**Comment by donavanbecker** [comment]
@Kratoskate28 Well none will definitely not display anything hence the logging of none.
Do you have any logs I can look at?

**Comment by Kratoskate28** [comment]
I hope that this helps.
[homebridge.log.txt](https://github.com/donavanbecker/homebridge-tuya-camera/files/7964730/homebridge.log.txt)

**Comment by JackCloudman** [comment]
I have the same problem with tuya, i installed the previous version and it works .___.

**Comment by Kratoskate28** [comment]
The previous version of the plugin or the homebridge itself?

**Comment by donavanbecker** [comment]
This plugin

**Comment by seekoner** [comment]
@donavanbecker do you plan to extend compatibility with smart life app?

**Comment by donavanbecker** [comment]
@seekoner If someone helps out, I would.

**Comment by seekoner** [comment]
@donavanbecker what do you need? I'm no programmer but I would be glad to help testing and stuff :)

**Comment by donavanbecker** [comment]
I need someone that knows ffmpeg ha

**Comment by Kratoskate28** [comment]
@donavanbecker Have you been able to find something in the log, that may cause issues? I tried the previous version of the tuya camera plugin and it tells me that I must make sure that my tuya platform has been created after may 25 2021 but I made it in october 2021...

**Comment by seekoner** [comment]
> I need someone that knows ffmpeg ha

Can't help with that tho 😅

**Comment by seekoner** [comment]
@donavanbecker just so you know, 
- i tried pairing my Tuya Camera with the Tuya App, 
- made a new cloud project with PaaS and everything
- Linked my app to the cloud project
but i can't make it work. this time i got this log 

[TuyaCamera] Attention !!! You get an error!
[TuyaCamera] Pease confirm that the access id and access secret of the smart home paas project you are using were created after may 25, 2021
[TuyaCamera] Please linked devices by using tuya smart in your cloud project.
[TuyaCamera] failed to get device information . please check if the config.json is correct.

i've checked multiple times, even tried every version of the plugin and no success.

**Comment by seekoner** [comment]
@donavanbecker i managed to get my RTSP and HLS streaming adresses via the tuya loT but can't make it work with FFmpeg... did you managed to make it work?

I must say that the URLs are very odd and seems to be could based.

Ffmpeg can't start streaming even with the url which is like "-i rtspi://xxxxx.."

Could you help?
Thanks

**Comment by donavanbecker** [comment]
I have got HLS to work. But this is a work in progress plugin that's why the verison is 0.0.3

**Comment by seekoner** [comment]
@donavanbecker Could you explain me how you did it? Would be greatly appreciated.

**Comment by donavanbecker** [comment]
Get the HLs stream open it up then add it to camera-ffmpeg, but then the stream times out after so long.

This is a work In Progress

**Comment by Kratoskate28** [comment]
I tried everything, very everything but I can’t get it to work and I have the exact same issue as @seekoner had 3h ago.

**Comment by seekoner** [comment]
> Get the HLs stream open it up then add it to camera-ffmpeg, but then the stream times out after so long.
> 
> This is a work In Progress 

@donavanbecker Yeah I've tried it, can't get it to work,

First where did you get the HLS stream? I got mine from Tuya loT Within the loT Video Live Stream > Request RTSP/HLS Live steam
And I have something like:
"Https://aws-tractor2.tuyaeu.com:8033/hls/xxxxxxxxxxxxxxxx.m3u8"

(Xxx is for Id redaction)

Also could you provide an example of your ffmpeg config.json so I can compare?

Thanks

**Comment by seekoner** [comment]
@donavanbecker I also have my cam's local ip if it's any help

**Comment by Kratoskate28** [comment]
Can I get some help pls??
