### ISSUE TITLE
Support Request:

### ISSUE THREAD

**Issue by JackCloudman** [donavanbecker/homebridge-tuya-camera#3]
### Describe Your Problem

I dont know how to use the rtsps URL in ffmpeg

### Screenshots

Hello I need some help, with v1.0.0 of the plugin I can get the URL for video camera stream, but, when I trying to connect, the URL always return 404 :/ 
The command that I use: 

`ffmpeg -i rtsps://echo:XXXXXXXXXXXXXXXXXX@aws-wework6.tuyaus.com:443/v1/XXXXXXXXXXXXXX/XXXXXXXXXXXXXX?signInfo=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX`

![image](https://user-images.githubusercontent.com/17970185/151708584-0974dfa7-ca1c-407b-8055-16a245655a16.png)

Its a problem with the version of the plugin? I tried with the last version but always return an error and don't log it.

### Device & Model

Steren CCTV-204

### Node.js Version

v16.13.2

### NPM Version

8.1.2

### Homebridge Version

1.4.0

### Homebridge Tuya Camera Plugin Version

v1.0.0

### Operating System

Raspbian

**Comment by donavanbecker** [comment]
@JackCloudman Try the HSL, the other thing your have to remember is that you have to get a new url after these time out. This is more to tie with camera-ffmpeg. We will be working on pushing these urls over there, but currently not possible

**Comment by 4ug3r** [comment]
same problem here

i still can't generate a hsl stream url.
Unfortunately I can't read anywhere how this url is generated or composed.

Please provide instructions on how to do this.

**Comment by donavanbecker** [comment]
@4ug3r this is a Work in Progress. Until we can get this tied with the Camera-Ffmpeg plugin.

**Comment by 4ug3r** [comment]
> @4ug3r this is a Work in Progress. Until we can get this tied with the Camera-Ffmpeg plugin.

Ok, thanks for the quick reply.
I thought it would be possible to test it already.
Then I will wait for newer versions.

Thanks for the work on this project.
